### PR TITLE
Setup React Native and Firebase

### PR DESCRIPTION
**Pull request by emmanuelvr**
## Description
Initial setup of React Native with Firebase

## Related Issue
https://github.com/jonathan-irvin/jelly-fin/issues/21

## How Has This Been Tested?
I made sure all the setup is working correctly.

## Types of changes
* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] Breaking change (fixes, design refactors, or anything that could cause existing functionality to change)
* [ ] New feature (non-breaking change which adds functionality)

## Checklist:
* [ ] My code follows the code style of this project.:
We still have to set up the linter and Flow.
* [x] My change required a change to the documentation.
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.
* [x] I have emulated in Android and tested my change.
* [x] I have emulated in iOS and tested my change.

### CODE REVIEW

**Comment by jonathan-irvin** [comment]
Relates to #21

**Comment by jonathan-irvin** [comment]
@emmanuelvr as of https://github.com/jonathan-irvin/jelly-fin/pull/24/commits/1ca90d76fc2843e0437e1a2b2d57c2522a360baa I believe I have merged in master to yours.  It'll be up to you to get the build to pass.  Don't worry about tests _as much_ just do a simple smoke test and that should be fine.

The build should pass before we merge this PR.  Modify `.travis.yml` as needed to make sure any dependencies are installed.  For a backlog item, let's create a GH issue to build multi-platforms.  Eventually, we will need to bake in a deployment process, but for now, let's settle on getting tests to pass and building locally.

I'd like to tighten up the setup process a bit and make sure there are clear expectations for developers wanting to contribute to the project.

To do that, we need to build out the scripts section of package.json and make it easy to digest.

Here's some expectations:

`npm postinstall` this is built into node, but we should define it in scripts.  After running install, we should check the versions of stuff to make sure all of the global packages are there.
`npm run setup` should install all of the prerequisites.  Don't worry about this now, we can separate this into a different GH issue.
`npm run ios` should just run `react-native run-ios`
`npm run android` should just run `react-native run-android`

**Comment by emmanuelvr** [comment]
The only extra installation that needs to be done is Cocoapods, which depends on the OS being macOS, so... It isn't necessary to add it to `.travis.yml`, right?

**Comment by jonathan-irvin** [comment]
> The only extra installation that needs to be done is Cocoapods, which depends on the OS being macOS, so... It isn't necessary to add it to `.travis.yml`, right?

Only if it is apart of the build process.  We can cross that bridge when we get there.  Just focus on getting us to a passing build and we can add to it from there.

**Review by jonathan-irvin — APPROVED** [review]
After making a couple of tweaks, I've got this locked down for now.  We can focus on building this up later.

**Pull request merged**
